use regex::Regex;
use serde_json::Value;
use std::sync::LazyLock;

static CLEAN_USER_QUERY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"<user_query>\s*").unwrap());
static CLEAN_END_QUERY_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\s*</user_query>").unwrap());
static CLEAN_ATTACHED_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<attached_files>.*?</attached_files>").unwrap());
static CLEAN_MULTI_NL_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"\n{3,}").unwrap());

static STRIP_TAGS: &[&str] = &[
    "open_and_recently_viewed_files",
    "user_info",
    "system_reminder",
    "system-reminder",
    "git_status",
    "external_links",
    "rules",
    "agent_skills",
    "manually_attached_skills",
    "recommended_plugins",
];

static STRIP_TAG_REGEXES: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    STRIP_TAGS
        .iter()
        .map(|tag| Regex::new(&format!(r"(?s)<{tag}>.*?</{tag}>")).unwrap())
        .collect()
});

static NOISE_PATTERNS: &[&str] = &[
    "this session is being continued",
    "caveat:",
    "you are claude code",
    "read-only mode",
    "i cannot make changes",
    "i'm in plan mode",
    "hello! i'm claude",
    "i am claude",
    "ready to help you",
    "what would you like me to",
    "how can i assist",
    "i understand that i'm",
];

static WARMUP_PATTERNS: &[&str] = &["warmup", "/clear"];

static CLEAR_META_PATTERNS: &[&str] = &[
    "caveat: the messages below were generated by the user while running local commands",
    "<command-name>",
    "</command-name>",
    "<local-command-stdout>",
];

fn truncate_for_search(s: &str, max: usize) -> String {
    if s.len() <= max {
        return s.to_owned();
    }
    let head_end = s.floor_char_boundary(max * 3 / 4);
    let tail_start = s.ceil_char_boundary(s.len().saturating_sub(max / 4));
    format!("{} {}", &s[..head_end], &s[tail_start..])
}

pub fn extract_text(content: &Value) -> String {
    match content {
        Value::String(s) => s.clone(),
        Value::Array(arr) => {
            let mut parts = Vec::new();
            for block in arr {
                let btype = block.get("type").and_then(Value::as_str).unwrap_or("");
                match btype {
                    // "input_text"/"output_text" are Codex content block types
                    "text" | "input_text" | "output_text" => {
                        if let Some(t) = block.get("text").and_then(Value::as_str) {
                            parts.push(t.to_string());
                        }
                    }
                    "tool_use" => {
                        let name = block.get("name").and_then(Value::as_str).unwrap_or("");
                        let mut tool_parts = vec![format!("[Tool: {name}]")];
                        if let Some(inp) = block.get("input").and_then(Value::as_object) {
                            for key in &[
                                "file_path",
                                "command",
                                "description",
                                "pattern",
                                "query",
                                "prompt",
                                "path",
                            ] {
                                if let Some(Value::String(val)) = inp.get(*key) {
                                    let truncated: String = val.chars().take(200).collect();
                                    tool_parts.push(truncated);
                                }
                            }
                        }
                        parts.push(tool_parts.join(" "));
                    }
                    "tool_result" => match block.get("content") {
                        Some(Value::String(inner)) => {
                            let truncated = truncate_for_search(inner, 16 * 1024);
                            parts.push(format!("[Tool Result] {truncated}"));
                        }
                        Some(Value::Array(arr)) => {
                            for item in arr {
                                if let Some(t) = item.get("text").and_then(Value::as_str) {
                                    let truncated = truncate_for_search(t, 16 * 1024);
                                    parts.push(format!("[Tool Result] {truncated}"));
                                }
                            }
                        }
                        _ => {}
                    },
                    _ => {}
                }
            }
            parts.join(" ")
        }
        _ => String::new(),
    }
}

#[derive(Default)]
pub struct MessageContext {
    pub tools: Vec<String>,
    pub files: Vec<String>,
    pub errors: Vec<String>,
}

pub fn extract_context(content: &Value) -> MessageContext {
    let mut ctx = MessageContext::default();
    let Some(arr) = content.as_array() else {
        return ctx;
    };
    for block in arr {
        let btype = block.get("type").and_then(Value::as_str).unwrap_or("");
        match btype {
            "tool_use" => {
                if let Some(name) = block.get("name").and_then(Value::as_str)
                    && !name.is_empty()
                {
                    ctx.tools.push(name.to_string());
                }
                if let Some(inp) = block.get("input").and_then(Value::as_object) {
                    for key in &["file_path", "path"] {
                        if let Some(Value::String(val)) = inp.get(*key) {
                            ctx.files.push(val.clone());
                        }
                    }
                }
            }
            "tool_result" => {
                let texts: Vec<String> = match block.get("content") {
                    Some(Value::String(s)) => vec![s.clone()],
                    Some(Value::Array(arr)) => arr
                        .iter()
                        .filter_map(|item| {
                            item.get("text").and_then(Value::as_str).map(String::from)
                        })
                        .collect(),
                    _ => Vec::new(),
                };
                for inner in &texts {
                    for line in inner.lines() {
                        let ll = line.to_lowercase();
                        if ["error", "exception", "traceback", "failed"]
                            .iter()
                            .any(|w| ll.contains(w))
                        {
                            let truncated: String = line.trim().chars().take(200).collect();
                            ctx.errors.push(truncated);
                        }
                    }
                }
            }
            _ => {}
        }
    }
    ctx
}

pub fn clean_prompt(text: &str) -> String {
    let mut result = CLEAN_USER_QUERY_RE.replace_all(text, "").to_string();
    result = CLEAN_END_QUERY_RE.replace_all(&result, "").to_string();
    result = CLEAN_ATTACHED_RE
        .replace_all(&result, "[attached files]")
        .to_string();
    for re in STRIP_TAG_REGEXES.iter() {
        result = re.replace_all(&result, "").to_string();
    }
    result = CLEAN_MULTI_NL_RE.replace_all(&result, "\n\n").to_string();
    result.trim().to_string()
}

// Preamble tags stripped from titles even when unclosed (truncated prompts
// often cut off before the closing tag). `user_query` is excluded — its body
// IS the title.
static TITLE_PREAMBLE_RES: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    STRIP_TAGS
        .iter()
        .chain(std::iter::once(&"timestamp"))
        .map(|tag| Regex::new(&format!(r"(?s)<{tag}>.*?(</{tag}>|\z)")).unwrap())
        .collect()
});
// Lowercase snake/kebab tags of ≥3 chars: catches machine preamble markup
// while leaving code-like tokens (`Vec<String>`, `<T>`) in titles.
static TITLE_LEFTOVER_TAG_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"</?[a-z][a-z0-9_-]{2,60}>").unwrap());
static TITLE_WS_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"\s+").unwrap());

/// Content-level cleaning for stored first prompts: strips preamble (even
/// when a closing tag is missing) and collapses whitespace, but keeps
/// code-like tokens and adds no display artifacts.
pub fn clean_first_prompt(text: &str) -> String {
    let mut t = clean_prompt(text);
    for re in TITLE_PREAMBLE_RES.iter() {
        t = re.replace_all(&t, " ").to_string();
    }
    TITLE_WS_RE.replace_all(t.trim(), " ").to_string()
}

/// One-line title for list/search rows: [`clean_first_prompt`] plus stray-tag
/// removal and ellipsis truncation on a char boundary. Returns "" when
/// nothing human-readable is left.
pub fn display_title(text: &str, max: usize) -> String {
    let t = clean_first_prompt(text);
    let t = TITLE_LEFTOVER_TAG_RE.replace_all(&t, " ");
    let t = TITLE_WS_RE.replace_all(t.trim(), " ").to_string();
    let mut out: String = t.chars().take(max).collect();
    if t.chars().count() > max {
        out.push('…');
    }
    out
}

pub fn is_noise(text: &str) -> bool {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return true;
    }
    let lower = trimmed.to_lowercase();
    NOISE_PATTERNS.iter().any(|p| lower.contains(p))
}

pub fn is_warmup_message(text: &str) -> bool {
    let stripped = text.trim().to_lowercase();
    WARMUP_PATTERNS.contains(&stripped.as_str())
}

pub fn is_clear_metadata(text: &str) -> bool {
    let lower = text.to_lowercase();
    CLEAR_META_PATTERNS.iter().any(|p| lower.contains(p))
}

pub fn is_clear_only_conversation(user_messages: &[String]) -> bool {
    if user_messages.is_empty() {
        return true;
    }
    user_messages.iter().all(|m| {
        let lower = m.trim().to_lowercase();
        lower.is_empty() || lower == "/clear" || lower == "clear" || is_clear_metadata(m)
    })
}

fn find_ci_position(haystack: &str, needle: &str) -> Option<usize> {
    let needle_lower: String = needle.to_lowercase();
    let needle_chars: Vec<char> = needle_lower.chars().collect();
    if needle_chars.is_empty() {
        return Some(0);
    }
    for (i, _) in haystack.char_indices() {
        let mut chars = haystack[i..].chars();
        let mut matched = true;
        for &nc in &needle_chars {
            match chars.next() {
                Some(hc) if hc.to_lowercase().next() == Some(nc) => {}
                _ => {
                    matched = false;
                    break;
                }
            }
        }
        if matched {
            return Some(i);
        }
    }
    None
}

pub fn snippet_around_match(text: &str, query: &str, context_chars: usize) -> String {
    let cleaned = clean_prompt(text);
    let query_terms: Vec<&str> = {
        let terms: Vec<&str> = query.split_whitespace().filter(|w| w.len() > 2).collect();
        if terms.is_empty() {
            query.split_whitespace().filter(|w| w.len() >= 2).collect()
        } else {
            terms
        }
    };
    let query_lower: Vec<String> = query_terms.iter().map(|t| t.to_lowercase()).collect();

    let phrase: String = query_lower.join(" ");
    let best_pos = if let Some(pos) = find_ci_position(&cleaned, &phrase) {
        pos
    } else {
        let mut positions = Vec::new();
        for t in &query_lower {
            if let Some(p) = find_ci_position(&cleaned, t) {
                positions.push(p);
            }
        }
        if positions.is_empty() {
            return cleaned.chars().take(context_chars).collect();
        }
        *positions.iter().min().unwrap()
    };

    let start = cleaned.floor_char_boundary(best_pos.saturating_sub(context_chars / 4));
    let end = cleaned.ceil_char_boundary((start + context_chars).min(cleaned.len()));

    let start = if start > 0 {
        let search_end = cleaned.ceil_char_boundary(start.saturating_add(30).min(cleaned.len()));
        cleaned[start..search_end]
            .find(' ')
            .map(|ws| start + ws + 1)
            .unwrap_or(start)
    } else {
        start
    };
    let end = if end < cleaned.len() {
        let search_start = cleaned.floor_char_boundary(end.saturating_sub(30));
        cleaned[search_start..end]
            .rfind(' ')
            .map(|ws| search_start + ws)
            .unwrap_or(end)
    } else {
        end
    };

    let end = end.max(start);
    let snippet = &cleaned[start..end.min(cleaned.len())];
    let prefix = if start > 0 { "..." } else { "" };
    let suffix = if end < cleaned.len() { "..." } else { "" };
    format!("{prefix}{snippet}{suffix}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn extract_text_from_string() {
        let v = json!("hello world");
        assert_eq!(extract_text(&v), "hello world");
    }

    #[test]
    fn extract_text_from_array() {
        let v = json!([
            {"type": "text", "text": "hello"},
            {"type": "text", "text": "world"}
        ]);
        assert_eq!(extract_text(&v), "hello world");
    }

    #[test]
    fn extract_text_tool_use() {
        let v = json!([
            {"type": "tool_use", "name": "Read", "input": {"file_path": "/src/main.rs"}}
        ]);
        let text = extract_text(&v);
        assert!(text.contains("Read"));
        assert!(text.contains("/src/main.rs"));
    }

    #[test]
    fn extract_text_tool_result_string() {
        let v = json!([
            {"type": "tool_result", "content": "some output text"}
        ]);
        let text = extract_text(&v);
        assert!(text.contains("some output text"));
    }

    #[test]
    fn extract_text_tool_result_array() {
        let v = json!([
            {"type": "tool_result", "content": [{"text": "result line"}]}
        ]);
        let text = extract_text(&v);
        assert!(text.contains("result line"));
    }

    #[test]
    fn extract_text_null() {
        assert_eq!(extract_text(&json!(null)), "");
    }

    #[test]
    fn extract_text_number() {
        assert_eq!(extract_text(&json!(42)), "");
    }

    #[test]
    fn clean_prompt_strips_user_query_tags() {
        assert_eq!(
            clean_prompt("<user_query> hello world </user_query>"),
            "hello world"
        );
    }

    #[test]
    fn clean_prompt_strips_attached_files() {
        let text = "hello <attached_files>some files here</attached_files> world";
        assert_eq!(clean_prompt(text), "hello [attached files] world");
    }

    #[test]
    fn clean_prompt_collapses_newlines() {
        assert_eq!(clean_prompt("hello\n\n\n\n\nworld"), "hello\n\nworld");
    }

    #[test]
    fn clean_prompt_strips_hyphenated_system_reminder() {
        // Claude Code injects hyphenated <system-reminder> blocks into user
        // message text; Cursor uses the underscore form.
        let text = "<system-reminder>\ninjected boilerplate\n</system-reminder>\nfix the login bug";
        assert_eq!(clean_prompt(text), "fix the login bug");
    }

    #[test]
    fn clean_prompt_strips_system_tags() {
        let text = "hello <system_reminder>internal stuff</system_reminder> world";
        assert_eq!(clean_prompt(text), "hello  world");
    }

    #[test]
    fn is_noise_empty_and_whitespace() {
        assert!(is_noise(""));
        assert!(is_noise("   "));
        assert!(is_noise("\t\n"));
        assert!(is_noise("  \n  \t  "));
    }

    #[test]
    fn is_noise_allows_short_messages() {
        assert!(!is_noise("hi"));
        assert!(!is_noise("ok"));
        assert!(!is_noise("yes"));
        assert!(!is_noise("no"));
        assert!(!is_noise("y"));
        assert!(!is_noise("n"));
        assert!(!is_noise("fix ci"));
        assert!(!is_noise("ls -la"));
        assert!(!is_noise("git rebase"));
        assert!(!is_noise("run tests"));
        assert!(!is_noise("do it"));
        assert!(!is_noise("why?"));
        assert!(!is_noise("thanks"));
    }

    #[test]
    fn is_noise_all_known_patterns() {
        assert!(is_noise(
            "this session is being continued from a previous one"
        ));
        assert!(is_noise("caveat: some important note here"));
        assert!(is_noise("You are Claude Code, an AI assistant"));
        assert!(is_noise("I'm currently in read-only mode"));
        assert!(is_noise("I cannot make changes to files"));
        assert!(is_noise("I'm in plan mode right now"));
        assert!(is_noise("Hello! I'm Claude, ready to help"));
        assert!(is_noise("I am Claude and I can help"));
        assert!(is_noise("I'm ready to help you with your project"));
        assert!(is_noise("What would you like me to work on?"));
        assert!(is_noise("How can I assist you today?"));
        assert!(is_noise("I understand that I'm in a sandbox"));
    }

    #[test]
    fn is_noise_patterns_are_case_insensitive() {
        assert!(is_noise("YOU ARE CLAUDE CODE, an advanced AI"));
        assert!(is_noise("Hello! I'M CLAUDE, ready to help"));
        assert!(is_noise("HOW CAN I ASSIST you?"));
    }

    #[test]
    fn is_noise_valid_content() {
        assert!(!is_noise("rebuild docker container with new config"));
        assert!(!is_noise("implement the authentication system"));
    }

    #[test]
    fn is_noise_does_not_false_positive_on_substrings() {
        assert!(!is_noise("the session data is persisted to disk"));
        assert!(!is_noise("help me understand the codebase"));
        assert!(!is_noise("make changes to the parser module"));
        assert!(!is_noise("I'm working on plan mode switching logic"));
    }

    #[test]
    fn is_noise_unicode_and_punctuation() {
        assert!(!is_noise("日本語テスト"));
        assert!(!is_noise("café"));
        assert!(!is_noise("..."));
        assert!(!is_noise("???"));
        assert!(!is_noise("🚀"));
    }

    #[test]
    fn warmup_messages() {
        assert!(is_warmup_message("warmup"));
        assert!(is_warmup_message("/clear"));
        assert!(is_warmup_message("  /clear  "));
        assert!(!is_warmup_message("hello world"));
        assert!(!is_warmup_message("clear the cache"));
    }

    #[test]
    fn clear_only_conversation_empty() {
        assert!(is_clear_only_conversation(&[]));
    }

    #[test]
    fn clear_only_conversation_clear_messages() {
        assert!(is_clear_only_conversation(&["/clear".to_string()]));
        assert!(is_clear_only_conversation(&[
            "clear".to_string(),
            "/clear".to_string()
        ]));
    }

    #[test]
    fn clear_only_conversation_real_messages() {
        assert!(!is_clear_only_conversation(&[
            "implement feature X".to_string()
        ]));
    }

    #[test]
    fn snippet_contains_query_term() {
        let text = "This is a long piece of text about implementing authentication with OAuth2 tokens and JWT validation for the API endpoint";
        let snippet = snippet_around_match(text, "authentication", 100);
        assert!(snippet.contains("authentication"));
    }

    #[test]
    fn snippet_fallback_on_no_match() {
        let text = "This is a long piece of text about implementing stuff for the project with lots of details";
        let snippet = snippet_around_match(text, "nonexistent_xyz_term", 100);
        assert!(!snippet.is_empty());
    }

    #[test]
    fn snippet_short_text() {
        let snippet = snippet_around_match("short text here", "short", 200);
        assert!(snippet.contains("short"));
    }

    #[test]
    fn snippet_does_not_panic_on_empty() {
        let snippet = snippet_around_match("", "query", 100);
        assert!(snippet.is_empty() || snippet.len() < 100);
    }

    #[test]
    fn extract_context_tool_uses() {
        let v = json!([
            {"type": "tool_use", "name": "Read", "input": {"file_path": "/src/main.rs"}},
            {"type": "tool_use", "name": "Edit", "input": {"file_path": "/src/lib.rs"}}
        ]);
        let ctx = extract_context(&v);
        assert_eq!(ctx.tools, vec!["Read", "Edit"]);
        assert_eq!(ctx.files, vec!["/src/main.rs", "/src/lib.rs"]);
    }

    #[test]
    fn extract_context_errors_from_tool_result() {
        let v = json!([
            {"type": "tool_result", "content": "Error: file not found\nSuccess: done"}
        ]);
        let ctx = extract_context(&v);
        assert_eq!(ctx.errors.len(), 1);
        assert!(ctx.errors[0].contains("Error"));
    }

    #[test]
    fn extract_context_no_tools() {
        let v = json!([{"type": "text", "text": "just text"}]);
        let ctx = extract_context(&v);
        assert!(ctx.tools.is_empty());
        assert!(ctx.files.is_empty());
        assert!(ctx.errors.is_empty());
    }

    #[test]
    fn extract_context_non_array() {
        let v = json!("just a string");
        let ctx = extract_context(&v);
        assert!(ctx.tools.is_empty());
    }

    #[test]
    fn is_clear_metadata_positive() {
        assert!(is_clear_metadata(
            "caveat: the messages below were generated by the user while running local commands"
        ));
        assert!(is_clear_metadata("some text with <command-name> tag"));
    }

    #[test]
    fn is_clear_metadata_negative() {
        assert!(!is_clear_metadata("implement the new feature"));
    }

    #[test]
    fn truncate_for_search_short() {
        assert_eq!(truncate_for_search("short", 100), "short");
    }

    #[test]
    fn truncate_for_search_long() {
        let long = "a".repeat(1000);
        let result = truncate_for_search(&long, 100);
        assert!(result.len() <= 200); // head + tail with space
    }

    #[test]
    fn display_title_strips_unclosed_preamble_tag() {
        let raw =
            "<manually_attached_skills>\nThe user has manually attached the following skills t";
        assert_eq!(display_title(raw, 80), "");
    }

    #[test]
    fn display_title_keeps_text_after_closed_preamble() {
        let raw =
            "<manually_attached_skills>skill stuff</manually_attached_skills>\nfix the login bug";
        assert_eq!(display_title(raw, 80), "fix the login bug");
    }

    #[test]
    fn display_title_collapses_newlines_to_one_line() {
        let raw = "fix the\n\nlogin   bug\ttoday";
        assert_eq!(display_title(raw, 80), "fix the login bug today");
    }

    #[test]
    fn display_title_truncates_with_ellipsis() {
        let raw = "a".repeat(100);
        let out = display_title(&raw, 10);
        assert_eq!(out.chars().count(), 11);
        assert!(out.ends_with('…'));
    }

    #[test]
    fn display_title_keeps_code_like_tokens() {
        assert_eq!(
            display_title("implement Vec<String> parsing for <T>", 80),
            "implement Vec<String> parsing for <T>"
        );
    }

    #[test]
    fn clean_first_prompt_no_ellipsis_and_keeps_code_tokens() {
        let raw = format!(
            "<manually_attached_skills>\nstuff\n</manually_attached_skills>\nfix Vec<String> bug {}",
            "y".repeat(400)
        );
        let out = clean_first_prompt(&raw);
        assert!(out.starts_with("fix Vec<String> bug"));
        assert!(!out.contains('…'));
        assert!(!out.contains("manually_attached_skills"));
    }

    #[test]
    fn display_title_strips_stray_tags_and_keeps_user_query_body() {
        let raw = "<user_query>how do I deploy this?</user_query>";
        assert_eq!(display_title(raw, 80), "how do I deploy this?");
        let raw2 = "<timestamp>2026-07-22T10:00:00Z</timestamp>ship the release";
        assert_eq!(display_title(raw2, 80), "ship the release");
    }
}
